version: "3.7"

network_mode: host
pid: host

services:
  satoshitop:
    image: st3b1t/satoshitop
    container_name: satoshitop
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      # bitcoin in host machine
      RPCCONNECT: 172.17.0.1
      # bitcoin rpc default port
      RPCPORT: 8332
